### ISSUE TITLE
Wireshark handler error on osx

### ISSUE THREAD

**Issue by marchemi** [KiraleTech/KiTools#1]
Live function fail on OSX with Wireshark Version 3.4.0 (v3.4.0-0-g9733f173ea5e)  (and older) / Python 3.7.7

see trace : 
macbookdemikael:KiTools ummo7442$ python -m kitools --channel 20 --live
****************************************************************************
**                              Kirale Tools                              **
****************************************************************************

Available Kirale devices:
1:  /dev/cu.usbmodem143102KSH  Sniffer v1.2.7749.46920       KTWM102-11+201802+8404D200000005DC  KTWM102 Module
cu.usbmodem143102|> show snum
cu.usbmodem143102|> KTWM102-11+201802+8404D200000005DC
cu.usbmodem143102|> clearEnter a valid path for Wireshark: /usr/local/bin/wireshark
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ummo7442/Documents/dev/CHIP/kirale/kirale_dongle/KiTools/kitools/__main__.py", line 257, in <module>
    main()
  File "/Users/ummo7442/Documents/dev/CHIP/kirale/kirale_dongle/KiTools/kitools/__main__.py", line 214, in main
    name = sniffer.config_pipe_handler()
  File "/Users/ummo7442/Documents/dev/CHIP/kirale/kirale_dongle/KiTools/kitools/kisniffer.py", line 137, in config_pipe_handler
    self.handlers.append(handler)
UnboundLocalError: local variable 'handler' referenced before assignment

**Comment by marchemi** [comment]
A way to solve, is to use a fifo: 
$ mkfifo /tmp/thread.cap
$ wireshark -k -i <(cat /tmp/thread.cap)
$ python -m kitools --channel 20 --file /tmp/thread.cap

**Comment by KiraleDev** [comment]
Thanks @marchemi for raising this bug.
The issue has been addressed in version 1.4.2
